version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: pupok48/foodgram_backend:latest
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: pupok48/foodgram_frontend:latest
    volumes:
      - static:/app/result_build/build

  nginx:
    image: pupok48/foodgram_gateway:latest
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
