version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: pupok48/foodgram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: pupok48/foodgram_frontend:latest
    env_file: .env
    volumes:
      - static:/app/result_build/build

  gateway:
    image: pupok48/foodgram_gateway:latest
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./foodgramproject.crt:/etc/nginx/foodgramproject.crt
      - ./foodgramproject.key:/etc/nginx/foodgramproject.key
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/