version: '3.3'

volumes:
  static_volume:
  media:
  postgres_data:

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: pupok48/foodgram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db

  frontend:
    image: pupok48/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
    volumes:
      - static:/app/result_build/build

  gateway:
    image: pupok48/foodgram_gateway:latest
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
