version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: pupok48/foodgram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    image: pupok48/foodgram_frontend:latest
    env_file: .env
    volumes:
      - static:/app/result_build/build

  nginx:
    image: pupok48/foodgram_gateway:latest
    ports:
      - 9090:80
    volumes:
      - static_volume:/static/
      - media:/app/media/