version: '3.3'

volumes:
  static:
  media:
  postgres_data:

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: pupok48/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db

  frontend:
    image: pupok48/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    env_file: .env
    volumes:
      - static:/static

  gateway:
    image: pupok48/foodgram_gateway:latest
    ports:
      - 9090:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - frontend
